export const FETCH_PRODUCTS_REQUEST="FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE="FETCH_PRODUCTS_FAILURE";
export const ADD_PRODUCTS_TO_CART="ADD_PRODUCTS_TO_CART";
export const REMOVE_PRODUCTS_FROM_CART="REMOVE_PRODUCTS_FROM_CART";
export const EMPTY_CART="EMPTY_CART";
